### PR TITLE
WIP: add missing methods on sdk.Operation

### PR DESCRIPTION
**Pull request by vtolstov**
pr lacks of Execute methods for FaasOperation where i can get it?

### CODE REVIEW

**Comment by s8sg** [comment]
This will break openfaas mate. I guess its time to maintain the faas-flow-lib in a different repository

**Comment by vtolstov** [comment]
Yes, this will be fine. Also exclude from lib openfaas stuff.

пт, 23 авг. 2019 г., 13:01 Swarvanu Sengupta <notifications@github.com>:

**Comment by s8sg** [comment]
@vtolstov Do you have any update on

**Comment by s8sg** [comment]
I added it as a part of PR #106

**Pull request closed without merging**
