### PR TITLE
Parse workflow name from host

### PR DESCRIPTION
**Pull request by s8sg**
With this PR, the environment `workflow_name` will not be required anymore
We are parsing the `Request.Host` to parse to function name. 

Fixes: #68 

Signed-off-by: s8sg <swarvanusg@gmail.com>

### CODE REVIEW

**Comment by s8sg** [comment]
@chennqqi This fixes #68 , can you please give it a try

**Comment by chennqqi** [comment]
OK

**Comment by chennqqi** [comment]
test passed
when i comment `workflow_name`, result is expect

**Comment by s8sg** [comment]
Great. Have you tested in K8s ?

**Comment by chennqqi** [comment]
Only tested in k8s. I don't have swarm environment.

**Comment by s8sg** [comment]
I just tested with swarm, works well. I'll merge the same

**Pull request merged**
